\i req/req1.sql
\i req/req2.sql
\i req/req3.sql
\i req/req4.sql
\i req/req5.sql
\i req/req6.sql
\i req/req7.sql
\i req/req8.sql
\i req/req9.sql
\i req/req10.sql
\i req/req11.sql
\i req/req12.sql
\i req/req13.sql
\i req/req14.sql
\i req/req15.sql
\i req/req16.sql
\i req/req17.sql
\i req/req18.sql