INSERT INTO commande(mail, adresse_livraison) VALUES ('Fusce@dignissim.net','12 rue de jspquoi, 75018, Paris');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('308', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514105');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('309', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514106');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('435', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514107');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('439', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514108');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('440', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514109');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('441', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514110');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('444', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514111');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('445', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514112');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('634', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514113');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('641', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514114');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('642', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514115');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('643', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514116');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('646', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514117');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('651', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514118');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('652', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514119');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('899', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514120');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('900', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514121');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('903', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514122');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('904', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514123');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('906', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514124');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('909', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514125');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('911', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514126');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('912', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514127');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('913', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514128');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('917', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514129');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('918', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514130');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('926', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514131');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1229', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514132');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1235', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514133');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1241', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514134');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1243', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514135');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1244', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514136');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1245', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514137');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1246', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514138');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1247', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514139');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1248', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514140');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1249', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514141');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1251', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514142');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1252', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514143');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1253', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514144');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1254', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514145');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1257', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514146');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1261', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514147');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1263', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514148');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1264', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514149');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1265', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514150');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1268', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514151');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2250', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514152');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1545', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514153');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1553', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514154');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1558', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514155');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1560', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514156');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1561', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514157');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1562', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514158');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1569', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514159');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1570', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514160');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1572', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514161');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1573', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514162');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1574', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514163');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1582', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514164');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1790', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514165');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1794', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514166');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1795', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514167');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1800', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514168');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1801', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514169');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1802', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514170');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1803', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514171');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1804', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514172');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1806', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514173');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1807', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514174');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1808', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514175');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1812', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514176');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1815', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514177');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1817', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514178');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1819', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514179');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1982', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514180');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1987', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514181');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('1988', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514182');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2113', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514183');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2114', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514184');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2115', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514185');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2121', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514186');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2248', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514187');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2258', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514188');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2419', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514189');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2427', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514190');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2429', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514191');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2538', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514192');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2547', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514193');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2698', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514194');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2705', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514195');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2706', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514196');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2707', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514197');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2711', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514198');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2712', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514199');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2715', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514200');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2717', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514201');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2718', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514202');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2724', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514203');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2729', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514204');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2730', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514205');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2731', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514206');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2792', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514207');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2793', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514208');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2798', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514209');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2801', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514210');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2805', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514211');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2808', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514212');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2809', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514213');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2810', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514214');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2857', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514215');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2859', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514216');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2861', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514217');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2888', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514218');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2938', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514219');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2940', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514220');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2941', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514221');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2942', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514222');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2995', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514223');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2996', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514224');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2998', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514225');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('2999', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514226');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3002', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514227');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3119', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514228');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3127', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514229');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3129', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514230');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3130', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514231');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3131', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514232');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3134', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514233');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3135', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514234');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3142', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514235');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3156', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514236');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3157', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514237');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3158', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514238');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3160', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514239');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3165', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514240');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3166', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514241');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3178', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514242');
INSERT INTO article(id_produit, num_lot, date_production) VALUES ('3179', 'WISKGOOD', NOW());
INSERT INTO article_commande(id_commande, id_article) VALUES ('51', '514243');
